apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-cleanup-sa
  namespace: gitlab
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-cleanup-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-cleanup-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-cleanup-role
subjects:
  - kind: ServiceAccount
    name: pod-cleanup-sa
    namespace: gitlab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-runner-pod-cleanup
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-runner-pod-cleanup
  template:
    metadata:
      labels:
        app: gitlab-runner-pod-cleanup
    spec:
      serviceAccountName: pod-cleanup-sa
      containers:
        - name: gitlab-runner-pod-cleanup
          image: registry.gitlab.com/gitlab-org/ci-cd/gitlab-runner-pod-cleanup:latest
          env:
            - name: POD_CLEANUP_KUBERNETES_NAMESPACES
              value: pipeline
            - name: POD_CLEANUP_LOG_LEVEL
              value: debug
          resources:
            requests:
              cpu: 20m
              memory: 300M
            limits:
              cpu: 1000m
              memory: 2G
