apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-mirrors
  namespace: pipeline
  labels:
    app: migrate-job
spec:
  template:
    metadata:
      labels:
        app: migrate-job
    spec:
      serviceAccountName: migration-notary
      containers:
      - name: migrate
        image: ghcr.io/spack/protected-publish:0.0.9
        command: ["/srcs/migrate.sh"]
        args:
          - s3://spack-binaries/develop/aws-pcluster-neoverse_v1
          - s3://spack-binaries/develop/aws-pcluster-x86_64_v4
          - s3://spack-binaries/develop/bootstrap-aarch64-darwin
          - s3://spack-binaries/develop/bootstrap-x86_64-linux-gnu
          - s3://spack-binaries/develop/build_systems
          - s3://spack-binaries/develop/data-vis-sdk
          - s3://spack-binaries/develop/developer-tools-aarch64-linux-gnu
          - s3://spack-binaries/develop/developer-tools-darwin
          - s3://spack-binaries/develop/developer-tools-x86_64_v3-linux-gnu
          - s3://spack-binaries/develop/e4s-cray-rhel
          - s3://spack-binaries/develop/e4s-neoverse-v2
          - s3://spack-binaries/develop/e4s-oneapi
          - s3://spack-binaries/develop/e4s-rocm-external
          - s3://spack-binaries/develop/e4s
          - s3://spack-binaries/develop/hep
          - s3://spack-binaries/develop/ml-darwin-aarch64-mps
          - s3://spack-binaries/develop/ml-linux-aarch64-cpu
          - s3://spack-binaries/develop/ml-linux-aarch64-cuda
          - s3://spack-binaries/develop/ml-linux-x86_64-cpu
          - s3://spack-binaries/develop/ml-linux-x86_64-cuda
          - s3://spack-binaries/develop/ml-linux-x86_64-rocm
          - s3://spack-binaries/develop/radiuss-aws-aarch64
          - s3://spack-binaries/develop/radiuss-aws
          - s3://spack-binaries/develop/radiuss
          - s3://spack-binaries/develop/tutorial
          - s3://spack-binaries/develop/windows-vis
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 3500m
            memory: 14G
            ephemeral-storage: "50G"
        volumeMounts:
        - name: keys
          mountPath: "/mnt/keys/signing"
          readOnly: true
        - name: ephemeral
          mountPath: "/tmp"
        env:
          # Tell tempfile.mkdtemp to use the ephemeral storage
          #     https://docs.python.org/3/library/tempfile.html#tempfile.mkdtemp
          - name: TMPDIR
            value: "/tmp"
      restartPolicy: Never
      volumes:
      - name: keys
        secret:
          secretName: spack-signing-key-encrypted
          optional: false
      - name: ephemeral
        emptyDir:
          sizeLimit: 50G

      nodeSelector:
        spack.io/node-pool: base  # pool for the runner
