---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metabase-postgresql
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp3
  volumeName: pvc-metabase
