---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: refresh-gitaly-bundle
  namespace: gitlab
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: refresh-gitaly-bundle
  namespace: gitlab
rules:
  - apiGroups: ["", "apps"]
    resources: ["deployments", "pods", "pods/exec"]
    verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: refresh-gitaly-bundle
  namespace: gitlab
subjects:
  - kind: ServiceAccount
    name: refresh-gitaly-bundle
roleRef:
  kind: Role
  name: refresh-gitaly-bundle
  apiGroup: rbac.authorization.k8s.io
