name: Check Docker Image Versions

on:
  pull_request:
    types:
      # Default values
      - opened
      - synchronize
      - reopened
      # Re-run if labels change
      - labeled
      - unlabeled


jobs:
  check-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Check for no-image-bump label on PR
        id: label-check
        env:
          GH_TOKEN: ${{ github.token }}
        continue-on-error: true
        run: |
          gh api -H "Accept: application/vnd.github+json" /repos/spack/spack-infrastructure/issues/${{ github.event.pull_request.number }}/labels \
            | jq '[.[].name]' \
            | jq -e 'any(. == "no-image-bump")'

      - name: Fetch the rest of the repo
        run: git fetch --no-tags --prune --depth=1 origin main
        if: steps.label-check.outcome == 'failure'

      - name: Check for modified directories that need an image bump
        if: steps.label-check.outcome == 'failure'
        run: ./.github/scripts/check_docker_image_versions.sh
