name: Build Docker Images

on:
  push:
    branches:
      - main
    paths:
      - analytics/**
      - images/**
      - .github/workflows/custom_docker_builds.yml
  pull_request:
    paths:
      - analytics/**
      - images/**
      - .github/workflows/custom_docker_builds.yml

jobs:
  check-modified-dirs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      matrix: ${{ steps.dataStep.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch the main branch
        run: git fetch --no-tags --prune --depth=1 origin main

      - id: dataStep
        run: |
          echo "matrix"=$(.github/scripts/get_custom_image_build_matrix.sh) >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: check-modified-dirs
    if: ${{ needs.check-modified-dirs.outputs.matrix  }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.check-modified-dirs.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Log in to the Container registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false

      - name: Build ${{ (github.ref == 'refs/heads/main' && 'and push ') || '' }}${{ matrix.docker-image }}
        id: docker-build-push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ${{ matrix.docker-image }}
          file: ${{ matrix.docker-image }}/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }} # only publish image on push to main
          tags: ${{ matrix.image-tags }}
          platforms: linux/amd64,linux/arm64

      - name: Image digest
        run: echo ${{ steps.docker-build-push.outputs.digest }}
